name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'master'
jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.14-slim

    services:
      mysql:
        image: mysql:5.7.24
        env:
          MYSQL_ROOT_PASSWORD: system76

      redis:
        image: redis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build
          restore-keys: |
             ${{ runner.os }}-build

      - name: Install Dependencies
        run: |
          apt update && apt install -y gcc g++ git imagemagick libmcrypt-dev make musl-dev openssl wkhtmltopdf
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compilation
        run: mix compile --force --warnings-as-errors

      - name: Run Tests
        run: mix test
        env:
          DB_HOST: mysql
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          REDIS_HOST: redis
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}

  Format:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.14-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build
          restore-keys: |
             ${{ runner.os }}-build

      - name: Install Dependencies
        run: |
          apt update && apt install -y gcc g++ git libmcrypt-dev make musl-dev openssl wkhtmltopdf
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Formatter
        run: mix format --check-formatted

  Credo:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.14-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Cache
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build
          restore-keys: |
             ${{ runner.os }}-build

      - name: Install Dependencies
        run: |
          apt update && apt install -y gcc g++ git libmcrypt-dev make musl-dev openssl wkhtmltopdf
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Credo
        run: mix credo
